#ifndef TYPES_H
#define TYPES_H

#define SYSTEM_CLOCK 20000000
#define CPU_CLOCK (SYSTEM_CLOCK/2)
#define PPU_CLOCK (SYSTEM_CLOCK/5)
#define PSG_CLOCK (SYSTEM_CLOCK/6)
#define CYCLES_PER_FRAME (CPU_CLOCK/60)
#define CYCLES_PER_FRAME_LINE (CPU_CLOCK/60/262)

#define CPU_CLOCK_DIVIDE 2
#define PPU_CLOCK_DIVIDE 5
#define PSG_CLOCK_DIVIDE 6

#endif